In [19]:
from neural_net import NeuralNet
import numpy as np


nn = NeuralNet(3, 3, 3, 1)

print(nn)
print(nn.wh_i)
print(nn.wh_o)

print(nn.predict([1]))

nn.train([1, 2, 3], [2, 1, 3])

[[-2.87677537 -1.89379322  4.3474182 ]
 [ 2.32206905 -2.34972149 -2.34882299]
 [-2.33660887  2.0855234   0.25850995]]
[[-0.18575305  1.2019427  -3.54271446]
 [ 0.34047036  2.40509373  1.49216007]
 [-1.46332343 -0.51401278 -3.38976788]]


ValueError: shapes (3,3) and (1,) not aligned: 3 (dim 1) != 1 (dim 0)

In [2]:
with open('data/mnist_train.csv', 'r') as file:
  train_d = file.readlines()

with open('data/mnist_test.csv', 'r') as file:
  test_d = file.readlines()

# print(train_d[:10])
# print(test_d[:10])



In [ ]:

# Convert a few images from str to ints
train = [x.split(",") for x in train_d[:100]]
train = [[int(x) for x in img] for img in train]

test = [x.split(",") for x in train_d[:100]]
test = [[int(x) for x in img] for img in test]


In [31]:
train_digs = [x[0] for x in train]
train_imgs = [x[1:] for x in train]

scaled_imgs = (np.asfarray(train_digs) / 255 * .99) + .01

all_targets = np.array([np.zeros(10) for _ in range(100)])
i = 0
for dig in train_digs:
  all_targets[i][dig] = .99
  i+=1


print(all_targets)





[[0.   0.   0.   0.   0.   0.99 0.   0.   0.   0.  ]
 [0.99 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.99 0.   0.   0.   0.   0.  ]
 [0.   0.99 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.99]
 [0.   0.   0.99 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.99 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.99 0.   0.   0.   0.   0.   0.  ]
 [0.   0.99 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.99 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.99 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.99 0.   0.   0.   0.  ]
 [0.   0.   0.   0.99 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.99 0.   0.   0.  ]
 [0.   0.99 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.99 0.   0.  ]
 [0.   0.   0.99 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.99 0.  ]
 [0.   0.   0.   0.   0.   0.   0.99 0.   0.  

In [33]:
input_n = 784
output_n = 10
hidden_n = int(784/2)
nn = NeuralNet(input_n, output_n, hidden_n, 1)

nn.train(scaled_imgs, all_targets)

ValueError: shapes (392,784) and (100,) not aligned: 784 (dim 1) != 100 (dim 0)