In [42]:
from neural_net import NeuralNet
import numpy as np


nn = NeuralNet(3, 3, 3, 1)

print(nn)
print(nn.wh_i)
print(nn.wh_o)

print(nn.predict([1, 1, 1]))



[[-1.18999761  0.40196952 -2.91580822]
 [-2.14865668  0.70278958 -0.74222198]
 [-3.46050703 -2.28733519 -2.53015748]]
[[ 0.1958484  -2.04572068  1.60766509]
 [ 0.07946623 -1.12527141  1.38964064]
 [-1.79087735  1.03847163  2.31802647]]
[0.44988278 0.47223044 0.51555642]


## Load the Dataset

In [43]:
with open('data/mnist_train.csv', 'r') as file:
  train_d = file.readlines()

with open('data/mnist_test.csv', 'r') as file:
  test_d = file.readlines()

# print(train_d[:10])
# print(test_d[:10])



## Prepare the data

In [44]:

# Convert a few images from str to ints
train = [x.split(",") for x in train_d]
train = [[int(x) for x in img] for img in train]

test = [x.split(",") for x in test_d]
test = [[int(x) for x in img] for img in test]


In [45]:
train_digs = [x[0] for x in train]
train_imgs = [x[1:] for x in train]


scaled_imgs = (np.asfarray(train_imgs) / 255 * .99) + .01

all_targets = np.array([np.zeros(10) for _ in range(len(train_digs))])
i = 0
for dig in train_digs:
  all_targets[i][dig] = .99
  i+=1


print(all_targets)


[[0.   0.   0.   ... 0.   0.   0.  ]
 [0.99 0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]
 ...
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   0.99 0.  ]]


## Create the Neural Net

In [46]:
input_n = 784
output_n = 10
hidden_n = 100
nn = NeuralNet(input_n, output_n, hidden_n, 1)


In [47]:
def accuracy(preds, true):
  acc = sum(1 for i in range(len(preds)) if preds[i] == true[i])/len(preds)
  return acc


# Seperate images and digit values

In [48]:
train_digs = [x[0] for x in train]
train_imgs = [x[1:] for x in train]


scaled_imgs = (np.asfarray(train_imgs) / 255 * .99) + .01

all_targets = np.array([np.zeros(10) for _ in range(len(train_digs))])
i = 0
for dig in train_digs:
  all_targets[i][dig] = .99
  i+=1

## Train the net


In [49]:
epochs = 10
for epoch in range(epochs):
  for i in range(len(scaled_imgs)):
    nn.train(scaled_imgs[i], all_targets[i])

## Prepare test data and predict

In [50]:
test_digs = [x[0] for x in test]
test_imgs = [x[1:] for x in test]
scaled_test_imgs = (np.asfarray(test_imgs) / 255 * .99) + .01

In [51]:
preds = []

for img in scaled_test_imgs:
  pred = list(nn.predict(img))
  preds.append(pred.index(max(pred)))

print(preds)
print(test_digs)

print(accuracy(preds, test_digs))

[7, 2, 1, 0, 4, 1, 4, 9, 6, 9, 0, 2, 9, 0, 1, 5, 9, 7, 8, 4, 9, 6, 6, 5, 4, 0, 7, 4, 0, 1, 3, 1, 3, 6, 7, 2, 7, 1, 8, 1, 1, 7, 4, 2, 5, 5, 1, 2, 4, 4, 6, 3, 9, 5, 6, 0, 4, 1, 9, 5, 7, 2, 4, 3, 7, 4, 2, 4, 3, 0, 7, 0, 3, 7, 1, 7, 3, 7, 9, 7, 7, 6, 2, 7, 8, 4, 7, 5, 6, 1, 3, 6, 9, 3, 1, 4, 1, 7, 6, 9, 6, 0, 5, 4, 9, 9, 2, 1, 9, 4, 8, 7, 3, 9, 7, 4, 4, 4, 9, 2, 3, 4, 7, 6, 4, 9, 0, 5, 8, 5, 6, 6, 8, 7, 8, 1, 0, 1, 6, 4, 6, 7, 7, 1, 2, 1, 8, 2, 0, 8, 9, 8, 9, 3, 1, 5, 6, 0, 3, 4, 4, 6, 5, 4, 6, 5, 4, 5, 1, 4, 4, 7, 2, 3, 2, 7, 1, 8, 1, 8, 1, 8, 1, 0, 8, 9, 8, 3, 0, 1, 1, 1, 0, 4, 0, 8, 1, 6, 4, 2, 3, 6, 1, 1, 1, 3, 9, 5, 2, 9, 4, 9, 9, 3, 9, 0, 3, 5, 5, 5, 7, 2, 2, 7, 1, 2, 8, 4, 1, 7, 1, 3, 8, 7, 7, 9, 2, 2, 4, 1, 5, 8, 0, 7, 2, 5, 0, 4, 4, 2, 4, 1, 9, 5, 7, 7, 3, 8, 2, 0, 8, 1, 7, 7, 5, 1, 8, 1, 0, 0, 3, 0, 1, 9, 9, 4, 1, 8, 2, 1, 8, 9, 7, 5, 9, 2, 8, 4, 1, 5, 5, 2, 9, 4, 0, 4, 0, 0, 8, 8, 6, 7, 1, 2, 4, 0, 2, 7, 4, 3, 3, 0, 0, 5, 1, 9, 5, 5, 3, 5, 1, 7, 9, 3, 0, 4, 2, 0, 7, 1, 1, 2, 1, 